'use strict';

/**
 * A clean clone must BUILD (#52).
 *
 * `src/renderer/src/main.tsx` (and App.tsx) import `@brand/logo.png?url`, the
 * `@brand` alias points at `docs/`, and `docs/logo.png` was generated by
 * `tools/make-logo.cjs` and never committed — so `npm run build` failed on every
 * fresh checkout, in CI included, for as long as the Build job carried
 * `continue-on-error: true`.
 *
 * The generator CANNOT be a build step: its last output is the macOS `.icns`,
 * produced by `iconutil`, which ships only with macOS. So the rasters are
 * committed (the SVG stays the source of truth, `npm run brand` regenerates),
 * and this is the check that they stay committed.
 *
 * Deliberately derived, not hardcoded: the alias map is read out of
 * electron.vite.config.ts and the imports out of the sources, so a NEW aliased
 * asset is covered the day it is added — which is exactly how logo.png slipped
 * through.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const yaml = require('js-yaml');

const ROOT = path.resolve(__dirname, '..');

/** The renderer alias map, straight from the vite config. */
function viteAliases() {
  const cfg = fs.readFileSync(path.join(ROOT, 'electron.vite.config.ts'), 'utf8');
  const block = cfg.match(/alias:\s*\{([^}]*)\}/);
  assert.ok(block, 'no renderer `alias:` block in electron.vite.config.ts');
  const map = new Map();
  for (const m of block[1].matchAll(/'([^']+)'\s*:\s*resolve\(__dirname,\s*'([^']+)'\)/g)) {
    map.set(m[1], m[2]);
  }
  assert.ok(map.size > 0, 'the alias block parsed to nothing — this test is checking air');
  return map;
}

/** Every renderer source file. */
function sources(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) sources(p, out);
    else if (/\.(tsx?|css|html)$/.test(e.name)) out.push(p);
  }
  return out;
}

// Only static assets: `@/foo` and `@shared/bar` are extensionless module
// specifiers that the bundler resolves through its own extension list, and are
// already covered by `npm run typecheck`.
const ASSET = /\.(png|svg|jpe?g|gif|webp|ico|woff2?)$/i;

test('every aliased asset the renderer imports exists at the path vite resolves it to', () => {
  const aliases = viteAliases();
  const found = [];

  for (const file of sources(path.join(ROOT, 'src/renderer'))) {
    const text = fs.readFileSync(file, 'utf8');
    // `from '@brand/logo.png?url'`, `import '@/x.css'`, `url('@brand/…')`.
    for (const m of text.matchAll(/['"](@[\w-]*\/[^'"]+)['"]/g)) {
      const spec = m[1].split('?')[0];
      const alias = [...aliases.keys()].find((a) => spec === a || spec.startsWith(`${a}/`));
      if (alias && ASSET.test(spec)) found.push({ file, spec, alias });
    }
  }

  // Vacuity guard: if the scan or the regex drifts, this test must fail loudly
  // rather than quietly pass over an empty list.
  assert.ok(
    found.some((f) => f.file.endsWith('main.tsx') && f.spec.startsWith('@brand/')),
    'the @brand import this test exists for (#52) was not seen — the scan has drifted'
  );

  const missing = found
    .map((f) => ({
      ...f,
      abs: path.join(ROOT, aliases.get(f.alias), f.spec.slice(f.alias.length + 1))
    }))
    .filter((f) => !fs.existsSync(f.abs))
    .map((f) => `${path.relative(ROOT, f.file)} imports ${f.spec} -> ${path.relative(ROOT, f.abs)}`);

  assert.deepEqual(missing, [],
    'these are generated brand assets that are not committed — run `npm run brand`, then commit them (#52)');
});

/**
 * 02-09 D-40: three more parsed-not-grepped, both-directions clauses guarding
 * the phone PWA bundle (`resources/phone/**`) — the same #52 failure mode
 * (dev works, packaged app 404s) applied to a second `extraResources` entry.
 */

const PHONE_DIR = path.join(ROOT, 'resources', 'phone');
const MANIFEST_PATH = path.join(PHONE_DIR, 'manifest.webmanifest');
const ICON_512_PATH = path.join(PHONE_DIR, 'icon-512.png');
const LOGO_PATH = path.join(ROOT, 'docs', 'logo.png');

test('the phone bundle has a packaging entry, parsed from electron-builder.yml, pointing at the committed directory', () => {
  const cfg = yaml.load(fs.readFileSync(path.join(ROOT, 'electron-builder.yml'), 'utf8'));
  assert.ok(Array.isArray(cfg.extraResources) && cfg.extraResources.length > 0,
    'extraResources parsed to nothing — this clause is checking air');
  const entries = cfg.extraResources.filter((e) => e && e.from === 'resources/phone');
  assert.equal(entries.length, 1, 'expected exactly one extraResources entry for resources/phone');
  assert.equal(entries[0].to, 'phone');

  const files = ['index.html', 'sw.js', 'manifest.webmanifest', 'icon-192.png', 'icon-512.png'];
  for (const f of files) {
    assert.ok(fs.existsSync(path.join(PHONE_DIR, f)), `resources/phone/${f} does not exist`);
  }
});

test("the manifest's own icon list resolves, at the sizes it declares", () => {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
  assert.ok(Array.isArray(manifest.icons) && manifest.icons.length >= 2,
    'manifest.icons parsed to fewer than 2 entries — this clause is checking air');
  for (const icon of manifest.icons) {
    const abs = path.join(PHONE_DIR, icon.src);
    assert.ok(fs.existsSync(abs), `manifest references missing icon ${icon.src}`);
    const buf = fs.readFileSync(abs);
    const width = buf.readUInt32BE(16);
    const height = buf.readUInt32BE(20);
    assert.equal(`${width}x${height}`, icon.sizes,
      `${icon.src} is really ${width}x${height} but the manifest declares ${icon.sizes}`);
  }
});

test('the 512 icon has not drifted from its source (docs/logo.png) — run `npm run brand` and re-copy if this fails', () => {
  const iconDigest = crypto.createHash('sha256').update(fs.readFileSync(ICON_512_PATH)).digest('hex');
  const logoDigest = crypto.createHash('sha256').update(fs.readFileSync(LOGO_PATH)).digest('hex');
  assert.equal(iconDigest, logoDigest,
    'resources/phone/icon-512.png no longer matches docs/logo.png — run `npm run brand`, then re-copy it as icon-512.png');
});

/**
 * T-P02-09-07: the phone's CSP authorises its inline <script>/<style> by
 * sha256 hash rather than 'unsafe-inline'. Recompute both digests from the
 * COMMITTED file and assert they match the digests embedded in the meta
 * CSP — an edited script/style with a stale hash ships a phone that
 * silently executes nothing, and no other check in this plan would catch
 * it (the file still parses, still has a <script> tag, still passes every
 * other clause).
 */
test("the phone's CSP script-src/style-src hashes match the committed inline <script>/<style> content", () => {
  const html = fs.readFileSync(path.join(PHONE_DIR, 'index.html'), 'utf8');
  function extractBetween(open, close) {
    const i = html.indexOf(open);
    const j = html.indexOf(close, i);
    assert.ok(i !== -1 && j !== -1, `could not find a ${open}...${close} block in index.html`);
    return html.slice(i + open.length, j);
  }
  const styleText = extractBetween('<style>', '</style>');
  const scriptText = extractBetween('<script>', '</script>');
  const realStyleHash = crypto.createHash('sha256').update(styleText, 'utf8').digest('base64');
  const realScriptHash = crypto.createHash('sha256').update(scriptText, 'utf8').digest('base64');

  const scriptMatch = /script-src 'sha256-([^']*)'/.exec(html);
  const styleMatch = /style-src 'sha256-([^']*)'/.exec(html);
  assert.ok(scriptMatch, 'no script-src sha256 hash found in the CSP meta tag');
  assert.ok(styleMatch, 'no style-src sha256 hash found in the CSP meta tag');

  assert.equal(scriptMatch[1], realScriptHash,
    'the CSP script-src hash does not match the committed <script> content — the phone would execute nothing');
  assert.equal(styleMatch[1], realStyleHash,
    'the CSP style-src hash does not match the committed <style> content — the phone would render unstyled');
});

/* ───── plan 04-17: GATE-05's countdown and VIGIL-01's strip on the phone ─────
 *
 * ACCEPTED RESIDUAL, stated rather than implied: nothing in this repo executes
 * `resources/phone/index.html`'s JavaScript, so the countdown's BEHAVIOUR has
 * no automated coverage here — only its text, its structure, and (below) the
 * one function that can be lifted out and run on its own. Three things bound
 * that gap, all named in 04-17-SUMMARY.md: plan 04-18 unit-tests the identical
 * rule table through the desktop's `formatRemaining` (wave 6) and OWNS the
 * phone-vs-desktop literal cross-check that belongs in THIS file once both
 * sides exist; plan 04-19 task 3 is the physical-device attempt.
 */

const PHONE_HTML_PATH = path.join(PHONE_DIR, 'index.html');
const occurrences = (hay, needle) => hay.split(needle).length - 1;

/** 04-UI-SPEC §S1 rule G-3's format table, copied here as a literal array with
 *  its source named — NOT imported from plan 04-18's `formatRemaining`, which
 *  does not exist until wave 6. A clause written a wave before the thing it
 *  reads is red for a wave and fails this plan's own wave gate. */
const G3_FORMAT_LITERALS = ['m ', 's left', 'expiring', 'expired'];

test('the phone renders a countdown re-derived from an anchor, never a decremented counter (rule G-3)', () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');

  // Positive: the anchor is recorded AND read; the duration is consumed.
  assert.ok(occurrences(html, 'receivedAt') >= 2, 'the countdown anchor must be both written and read');
  assert.ok(occurrences(html, 'expiresInMs') >= 2, 'the server-measured duration must be consumed');

  // Negative, paired with the positives above so an empty file cannot satisfy
  // it: a DEADLINE timestamp never reaches a client whose clock is not ours.
  assert.equal(/expiresAt/i.test(html), false, 'a deadline timestamp must never appear on the phone');

  // Two gates, not one OR'd expression. Positive: exactly one new 1000ms
  // re-derivation beside the pre-existing 10s poll (measured at wave start: 1).
  assert.equal(occurrences(html, 'setInterval'), 2,
    'exactly one interval was added — the 1000ms re-derivation, beside the existing 10s poll');
  // Negative: nothing decrements a counter. A backgrounded tab makes a
  // decremented counter drift arbitrarily far in the OPTIMISTIC direction.
  assert.equal(/remaining\s*--|remaining\s*-=|--\s*remaining/.test(html), false,
    'the countdown must be re-derived from the anchor, never decremented');

  for (const literal of G3_FORMAT_LITERALS) {
    assert.ok(html.includes(`'${literal}'`) || html.includes(`+ '${literal}'`),
      `rule G-3's format table literal ${JSON.stringify(literal)} is missing from the phone`);
  }
  // The two states that govern the decision controls, and the branch that
  // keys the disable on the ≤0 case.
  assert.ok(/if\s*\(!\(ms > 0\)\)\s*return 'expired';/.test(html),
    "the ≤0 state's literal must be `expired`");
  assert.ok(/if\s*\(ms < 10000\)\s*return 'expiring';/.test(html),
    "the <10s state's literal must be `expiring` — no number is shown in the window where skew could lie");
  assert.ok(/var expired = !\(remaining > 0\);/.test(html) && /state\.sending \|\| expired \|\| /.test(html),
    'the decision-control disable must be keyed on the ≤0 branch');
});

test('the floor-quiet strip is a pinned, NON-interactive slot — not a third ask kind (rule Q-1b)', () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');

  // Occurrences, not lines: the repo documents that exact trap at
  // test/repo-claims.test.cjs:1325-1329.
  assert.ok(occurrences(html, 'p-quiet-bar') >= 2, 'the strip needs both a CSS rule and a render');

  // The criterion this replaces read "`data-action` count is unchanged", whose
  // stated reason is "the strip added no handler". Task 2 also adds the two
  // decision buttons, which legitimately DO need handlers, so the literal form
  // could not pass on correct code (the T-04-ASK-37 shape). This asserts the
  // property that criterion names, on the markup that names it.
  const renderLine = html.split('\n').find((l) => l.includes("class=\"p-quiet-bar\""));
  assert.ok(renderLine, 'no p-quiet-bar render found');
  assert.equal(/data-action|<button/.test(renderLine), false,
    'the strip is not interactive and does not pretend to be: no button, no handler');
  assert.ok(/role="status"/.test(renderLine), 'the strip is announced politely, never as an interruption');

  const cssBlock = html.slice(html.indexOf('.p-quiet-bar {'), html.indexOf('.p-empty {'));
  assert.ok(cssBlock.includes('var(--p-warn-fill)') && cssBlock.includes('inset 2px 0 0 var(--p-warn)'),
    'the strip is .p-offline-bar geometry in the warn register');
  assert.equal(/cursor/.test(cssBlock), false, 'no cursor change — there is nothing to tap');

  // It rides its OWN state slot. Overloading `state.banner` would make one of
  // two co-occurring facts invisible.
  assert.ok(html.includes('state.floorQuiet'), 'the alarm has its own state slot, not the offline banner\'s');
  assert.equal(/kind === 'alarm'|kind: 'alarm'/.test(html), false,
    'there is NO third ask kind — an alarm in the asks array renders "NEEDS YOU 1" when nothing is asking');

  // 04-UI-SPEC §S6a's three copy cases, formatted client-side. The dynamic
  // parts are interpolated, so these are the literal fragments the source
  // really carries.
  for (const fragment of [
    'The floor has stopped. Nothing has moved for ',
    'No cards were in flight.',
    ' cards were in flight.',
    ' is gone. The floor has no orchestrator, and nothing has moved for '
  ]) {
    assert.ok(html.includes(fragment), `the floor-quiet copy fragment ${JSON.stringify(fragment)} is missing`);
  }
});

test('an agent-authored command is escaped by the SAME helper title/question already use (T-04-ASK-35)', () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');

  // The command lands in `ask.question`, and every render of it on this
  // surface goes through escapeHtml — the phone has no framework escaping text
  // children for it, unlike the desktop (plan 04-14).
  for (const site of ['p-ask-cmd', 'p-command']) {
    const line = html.split('\n').find((l) => l.includes(`'${site}'`) || l.includes(`class="${site}"`));
    assert.ok(line, `no render found for .${site}`);
    assert.ok(line.includes('escapeHtml(ask.question)'),
      `.${site} interpolates the command without escapeHtml — the phone builds markup by concatenation`);
  }

  // Lift the real helper out of the committed file and run it, so this is the
  // shipped implementation rather than a re-statement of it.
  const src = html.match(/function escapeHtml\(s\) \{[\s\S]*?\n {2}\}/);
  assert.ok(src, 'escapeHtml was not found in the phone bundle');
  const escapeHtml = new Function(`${src[0]}; return escapeHtml;`)();

  const attack = '<img src=x onerror=alert(1)>';
  const out = escapeHtml(attack);
  assert.ok(out.includes('&lt;'), 'the command must appear as TEXT');
  assert.equal(out.includes('<img'), false, 'nothing in the command may open a tag, so nothing can become an attribute');
  assert.equal(out.includes('"'), false, 'quotes are escaped too — the command also lands inside an attribute value');
  // Positive control: a harmless command survives readable, so "escape
  // everything to nothing" cannot pass this.
  assert.equal(escapeHtml('rm -rf ./build/vendor'), 'rm -rf ./build/vendor');
});

/** Lift one top-level helper out of the committed bundle and return its source.
 *  Every helper in the IIFE is indented two spaces and closes on `\n  }`. */
function phoneFn(html, name) {
  const m = html.match(new RegExp(`function ${name}\\([^)]*\\) \\{[\\s\\S]*?\\n {2}\\}`));
  assert.ok(m, `${name} was not found in the phone bundle`);
  return m[0];
}

test('the phone bundle is syntactically valid — nothing else in this repo parses it', () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');
  const i = html.indexOf('<script>');
  const j = html.indexOf('</script>', i);
  assert.ok(i !== -1 && j !== -1, 'no inline <script> block found');
  const script = html.slice(i + '<script>'.length, j);
  // The CSP hash clause above happily passes on a bundle that throws on load:
  // it digests bytes, not syntax. This is the only thing standing between a
  // typo in a hand-written, framework-free bundle and a phone that boots to a
  // blank screen with no local reproduction.
  assert.doesNotThrow(() => new (require('node:vm').Script)(script, { filename: 'phone-inline.js' }));
  assert.ok(script.split('\n').length > 100, 'the extracted script is too short to be the real bundle');
});

/* This is the accepted residual, made smaller rather than merely restated: the
 * rule-G-3 formatter and the rule-Q-1b copy function are PURE, so they can be
 * lifted out of the committed bundle and run for real. What stays uncovered is
 * the render path and the interval, not the rules themselves. */
test("rule G-3's format table, executed against the shipped implementation", () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');
  const formatRemaining = new Function(`${phoneFn(html, 'formatRemaining')}; return formatRemaining;`)();

  assert.equal(formatRemaining(124_000), '2m 04s left', '≥60s — the seconds field is zero-padded');
  assert.equal(formatRemaining(60_000), '1m 00s left');
  assert.equal(formatRemaining(45_000), '45s left', '10–59s — a bare seconds count');
  assert.equal(formatRemaining(10_000), '10s left', 'the boundary belongs to the number, not to `expiring`');
  assert.equal(formatRemaining(9_999), 'expiring', '<10s — NO number, because that is the window skew could lie in');
  assert.equal(formatRemaining(1), 'expiring');
  assert.equal(formatRemaining(0), 'expired');
  assert.equal(formatRemaining(-5_000), 'expired', 'a negative remainder is expired, never a negative countdown');
  assert.equal(formatRemaining(undefined), 'expired', 'a missing duration fails to the SAFE side');
});

/* ─── Rule G-3 across BOTH implementations (plan 04-18, wave 6) ──────────────
 *
 * Two hand-written implementations of one rule table, in two languages, in two
 * files, with no shared module possible: the phone bundle is framework-free
 * inline script served to a device, and the desktop is a `.tsx` in the renderer
 * bundle. So the only honest check is to EXTRACT AND EXECUTE BOTH and compare
 * their outputs — never either against a third copy of the table written here,
 * which is a check that passes while both implementations are wrong together.
 *
 * THE CLAUSE LIVES IN WAVE 6, not with plan 04-17's phone work in wave 5,
 * because `formatRemaining` does not exist on the desktop until this wave and a
 * clause written before the thing it reads is red for a wave.
 *
 * AND IT IS NOT A BYTE-IDENTITY CHECK ON ALL FOUR BANDS. 04-UI-SPEC makes the
 * fourth band deliberately different — the phone renders `expiring`, the desktop
 * renders `expiring — will deny`. A blanket identity clause would be "fixed" by
 * deleting the desktop suffix, which is the only half of the string that tells a
 * 3am operator what the timeout DOES.
 */
test('rule G-3: the phone and the desktop agree on the three shared bands, and diverge on the fourth ON PURPOSE', () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');
  const phone = new Function(`${phoneFn(html, 'formatRemaining')}; return formatRemaining;`)();
  // The desktop's, out of the shipped .tsx. `BlockedBanner` imports `BlockReason`
  // as a TYPE only, so the transpile erases it and the module loads without the
  // renderer-alias shim this file does not carry.
  const { formatRemaining: desktop } = require('./load-ts.cjs')(
    'src/renderer/src/components/BlockedBanner.tsx'
  );
  assert.equal(typeof desktop, 'function',
    'BlockedBanner.tsx no longer exports formatRemaining — the rule table has gone back to being unassertable');

  // 1. BYTE-IDENTICAL on the three shared bands. Both sides extracted, neither
  //    compared against a literal written in this file.
  for (const ms of [124_000, 60_000, 45_000, 10_000, 0, -5_000]) {
    assert.equal(desktop(ms).text, phone(ms),
      `the two countdowns disagree at ${ms}ms: desktop ${JSON.stringify(desktop(ms).text)} vs phone ${JSON.stringify(phone(ms))}. One operator reads both surfaces, often within the same minute, and a countdown that says two different things about one ask is the state they cannot act on`);
  }

  // 2. The shared TOKENS survive on both sides — a positive lower bound, so an
  //    extraction that returned empty strings could not satisfy clause 1 above.
  const phoneSet = [124_000, 45_000, 9_000, 0].map(phone);
  const desktopSet = [124_000, 45_000, 9_000, 0].map((ms) => desktop(ms).text);
  for (const token of ['m ', 's left', 'expired']) {
    assert.ok(phoneSet.some((s) => s.includes(token)), `rule G-3's ${JSON.stringify(token)} is gone from the phone`);
    assert.ok(desktopSet.some((s) => s.includes(token)), `rule G-3's ${JSON.stringify(token)} is gone from the desktop`);
  }

  // 3. The <10s band, asserted in the one shape that keeps the divergence honest:
  //    the desktop literal STARTS WITH the phone's, and the remainder is exactly
  //    the desktop's extra clause. This fails if either side drifts, and it fails
  //    if someone "aligns" the two by deleting the suffix.
  const [pShort, dShort] = [phone(9_000), desktop(9_000).text];
  assert.ok(dShort.startsWith(pShort),
    `the desktop's <10s literal ${JSON.stringify(dShort)} no longer starts with the phone's ${JSON.stringify(pShort)} — the two surfaces have drifted into unrelated wordings for the same state`);
  assert.equal(dShort.slice(pShort.length), ' — will deny',
    'the desktop lost the half of its <10s string that says what the timeout DOES. `expiring` alone tells a 3am operator the clock is running; `— will deny` tells them which way it lands if they do nothing');

  // Neither side shows a NUMBER below ten seconds — the window where clock skew
  // and transit latency could lie.
  for (const [name, s] of [['phone', pShort], ['desktop', dShort]]) {
    assert.doesNotMatch(s, /[0-9]/,
      `the ${name}'s <10s state shows a number, in exactly the window where a number can lie about how much time is left`);
  }
});

/**
 * One exported TypeScript function, EXECUTED out of the file that ships it.
 *
 * `App.tsx` cannot be loaded by any harness in this repo — `:292` reads
 * `import.meta.env.DEV`, which throws `Cannot use 'import.meta' outside a module`
 * under the CommonJS transpile every test loader here uses. So the function is
 * lifted and transpiled on its own, which is `phoneFn`'s trick applied to TS. The
 * `typescript` package is already what `test/load-ts.cjs` runs on; nothing new is
 * installed.
 */
function tsFn(rel, name) {
  const ts = require('typescript');
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const m = src.match(new RegExp(`export function ${name}\\([^)]*\\)[^{]*\\{[\\s\\S]*?\\n\\}`));
  assert.ok(m, `${name} was not found as an exported function in ${rel}`);
  const js = ts.transpileModule(m[0].replace(/^export /, ''), {
    compilerOptions: { target: ts.ScriptTarget.ES2022 }
  }).outputText;
  return new Function(`${js}; return ${name};`)();
}

test('rule Q-1b: the phone and the desktop render the SAME quiet duration, executed on both sides', () => {
  // One operator reads both surfaces, often within the same minute. A phone that
  // says `32m` beside a titlebar that says `1920000ms` — or `31m` — is a floor whose
  // two reports of one fact disagree, and the operator has to work out which is lying
  // before they can act on either.
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');
  const phone = new Function(`${phoneFn(html, 'humanDuration')}; return humanDuration;`)();
  const desktop = tsFn('src/renderer/src/App.tsx', 'humanQuietFor');

  for (const ms of [0, 29_000, 31_000, 60_000, 1_920_000, 3_600_000, 3_840_000, 90_000_000]) {
    assert.equal(desktop(ms), phone(ms),
      `the quiet duration differs at ${ms}ms: desktop ${JSON.stringify(desktop(ms))} vs phone ${JSON.stringify(phone(ms))}`);
  }

  // Positive lower bound over both, so an extraction that returned '' for everything
  // could not satisfy the equality above.
  assert.equal(desktop(1_920_000), '32m', 'the 32-minute case is the one 04-UI-SPEC works its copy through');
  assert.equal(desktop(3_840_000), '1h 4m', 'past an hour the label must carry both fields');

  // Minutes are the resolution, on both sides: a seconds field on a five-minute
  // absence threshold is noise at 3am.
  assert.doesNotMatch(desktop(1_920_000), /s\b/, 'the desktop label grew a seconds field');
});

test("rule Q-1b's three copy cases, executed against the shipped implementation", () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');
  const body = html.match(/floorQuiet: function \(q\) \{[\s\S]*?\n {4}\}/);
  assert.ok(body, 'the floor-quiet copy function was not found');
  const floorQuiet = new Function(
    `${phoneFn(html, 'humanDuration')}; var COPY = { ${body[0]} }; return COPY.floorQuiet;`
  )();

  assert.equal(floorQuiet({ sinceMs: 1_920_000, inFlight: 2 }),
    'The floor has stopped. Nothing has moved for 32m. 2 cards were in flight.');
  assert.equal(floorQuiet({ sinceMs: 1_920_000, inFlight: 0 }),
    'The floor has stopped. Nothing has moved for 32m. No cards were in flight.');
  assert.equal(floorQuiet({ sinceMs: 1_920_000, inFlight: 2, agent: 'Michael' }),
    'Michael is gone. The floor has no orchestrator, and nothing has moved for 32m.');
  // Grammar, because a strip that reads "1 cards were in flight" at 3am reads
  // as a broken floor.
  assert.equal(floorQuiet({ sinceMs: 1_920_000, inFlight: 1 }),
    'The floor has stopped. Nothing has moved for 32m. 1 card was in flight.');
  // The duration is a DURATION: no timestamp, no date, no clock of the phone's.
  assert.match(floorQuiet({ sinceMs: 3_840_000, inFlight: 0 }), /1h 4m/);
});

test('rule G-1 holds on the phone: not one taskId was renamed', () => {
  const html = fs.readFileSync(PHONE_HTML_PATH, 'utf8');
  const sw = fs.readFileSync(path.join(PHONE_DIR, 'sw.js'), 'utf8');
  // OCCURRENCES, not lines. `grep -c` measures 15 here and 5 there because
  // several lines carry two each — a line-count gate could not pass on correct
  // code. Measured at wave start: 21 and 10.
  assert.ok(occurrences(html, 'taskId') >= 21, 'a taskId was renamed in index.html');
  assert.equal(occurrences(sw, 'taskId'), 10,
    'sw.js is INSTALLED on the operator\'s phone: a rename there is a live-device failure with no local reproduction');
  assert.equal(occurrences(sw, "'ask:'"), 1, 'the notification tag scheme was not touched');
});
