'use strict';

/**
 * A clean clone must BUILD (#52).
 *
 * `src/renderer/src/main.tsx` (and App.tsx) import `@brand/logo.png?url`, the
 * `@brand` alias points at `docs/`, and `docs/logo.png` was generated by
 * `tools/make-logo.cjs` and never committed — so `npm run build` failed on every
 * fresh checkout, in CI included, for as long as the Build job carried
 * `continue-on-error: true`.
 *
 * The generator CANNOT be a build step: its last output is the macOS `.icns`,
 * produced by `iconutil`, which ships only with macOS. So the rasters are
 * committed (the SVG stays the source of truth, `npm run brand` regenerates),
 * and this is the check that they stay committed.
 *
 * Deliberately derived, not hardcoded: the alias map is read out of
 * electron.vite.config.ts and the imports out of the sources, so a NEW aliased
 * asset is covered the day it is added — which is exactly how logo.png slipped
 * through.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');

/** The renderer alias map, straight from the vite config. */
function viteAliases() {
  const cfg = fs.readFileSync(path.join(ROOT, 'electron.vite.config.ts'), 'utf8');
  const block = cfg.match(/alias:\s*\{([^}]*)\}/);
  assert.ok(block, 'no renderer `alias:` block in electron.vite.config.ts');
  const map = new Map();
  for (const m of block[1].matchAll(/'([^']+)'\s*:\s*resolve\(__dirname,\s*'([^']+)'\)/g)) {
    map.set(m[1], m[2]);
  }
  assert.ok(map.size > 0, 'the alias block parsed to nothing — this test is checking air');
  return map;
}

/** Every renderer source file. */
function sources(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) sources(p, out);
    else if (/\.(tsx?|css|html)$/.test(e.name)) out.push(p);
  }
  return out;
}

// Only static assets: `@/foo` and `@shared/bar` are extensionless module
// specifiers that the bundler resolves through its own extension list, and are
// already covered by `npm run typecheck`.
const ASSET = /\.(png|svg|jpe?g|gif|webp|ico|woff2?)$/i;

test('every aliased asset the renderer imports exists at the path vite resolves it to', () => {
  const aliases = viteAliases();
  const found = [];

  for (const file of sources(path.join(ROOT, 'src/renderer'))) {
    const text = fs.readFileSync(file, 'utf8');
    // `from '@brand/logo.png?url'`, `import '@/x.css'`, `url('@brand/…')`.
    for (const m of text.matchAll(/['"](@[\w-]*\/[^'"]+)['"]/g)) {
      const spec = m[1].split('?')[0];
      const alias = [...aliases.keys()].find((a) => spec === a || spec.startsWith(`${a}/`));
      if (alias && ASSET.test(spec)) found.push({ file, spec, alias });
    }
  }

  // Vacuity guard: if the scan or the regex drifts, this test must fail loudly
  // rather than quietly pass over an empty list.
  assert.ok(
    found.some((f) => f.file.endsWith('main.tsx') && f.spec.startsWith('@brand/')),
    'the @brand import this test exists for (#52) was not seen — the scan has drifted'
  );

  const missing = found
    .map((f) => ({
      ...f,
      abs: path.join(ROOT, aliases.get(f.alias), f.spec.slice(f.alias.length + 1))
    }))
    .filter((f) => !fs.existsSync(f.abs))
    .map((f) => `${path.relative(ROOT, f.file)} imports ${f.spec} -> ${path.relative(ROOT, f.abs)}`);

  assert.deepEqual(missing, [],
    'these are generated brand assets that are not committed — run `npm run brand`, then commit them (#52)');
});
